## Numpy

In [2]:
!pip install numpy 

In [3]:
import numpy as np

In [5]:
a = np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [6]:
type(a)

numpy.ndarray

In [9]:
b = a.reshape(3,3)
b
#print(b)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
b.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
np.transpose(b)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [16]:
c = np.arange(8).reshape(2,4)
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [17]:
d=c.reshape(2,2,2)
d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [18]:
e = np.arange(9).reshape(3,3)
e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
f = np.array([4,5,6])
f

array([4, 5, 6])

In [24]:
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (9,) (3,3) 

In [30]:
s = np.arange(20)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
a[:6]

array([0, 1, 2, 3, 4, 5])

In [31]:
for i in np.nditer(s):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [32]:
np.split(a,[3,5,7])

[array([0, 1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]

## Pandas